package hermes

// This file contains version-specific Hermes bytecode opcode tables for
// versions other than 99 (which lives in opcodes.go as
// buildOpcodeTable99, hand-verified byte-for-byte against hermes-dec's
// Python reference table).
//
// Hermes bytecode's opcode-to-number mapping is NOT stable across bytecode
// format versions: instructions get added, removed, or renumbered between
// releases, which shifts every opcode number after the change point. A
// single hardcoded opcode table can only correctly decode files whose
// version matches that table; using it on a file from a different version
// silently produces wrong instruction names, wrong operand sizes, and
// (since operand sizes differ) a cascading misalignment of everything that
// follows in the bytecode stream.
//
// Each function below was generated directly from the corresponding
// hermes-dec/src/hermes_dec/parsers/hbc_opcodes/hbcNN.py file (the
// reference Python implementation) rather than transcribed by hand, and
// cross-checked field-for-field against that source, specifically to
// avoid the kind of transcription error that a hand-written table is prone
// to (two were found and fixed in the v99 table this same way: a wrong
// operand type on CallWithNewTargetLong that would have corrupted
// instruction sizes, and a spurious string_id meaning on DefineOwnById).
// buildOpcodeTable97 returns the Hermes bytecode opcode table for
// bytecode format version 97, ported directly from hermes-dec's
// hbc_opcodes/hbc97.py (the reference Python implementation), so it
// stays byte-for-byte consistent with what the real hermes-dec disassembler
// decodes for files of this version.
func buildOpcodeTable97() map[byte]*InstructionDef {
	t := make(map[byte]*InstructionDef)

	def := func(name string, opcode int, operands []OperandType, meanings []OperandMeaning, hasRet bool) {
		t[byte(opcode)] = NewInst(name, opcode, operands, meanings, hasRet)
	}

	noMeaning := func(n int) []OperandMeaning {
		m := make([]OperandMeaning, n)
		for i := range m {
			m[i] = MeaningNone
		}
		return m
	}

	def("Unreachable", 0, nil, nil, false)
	def("NewObjectWithBuffer", 1, []OperandType{Reg8, UInt16, UInt16}, noMeaning(3), false)
	def("NewObjectWithBufferLong", 2, []OperandType{Reg8, UInt32, UInt32}, noMeaning(3), false)
	def("NewObject", 3, []OperandType{Reg8}, noMeaning(1), false)
	def("NewObjectWithParent", 4, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("NewArrayWithBuffer", 5, []OperandType{Reg8, UInt16, UInt16, UInt16}, noMeaning(4), false)
	def("NewArrayWithBufferLong", 6, []OperandType{Reg8, UInt16, UInt16, UInt32}, noMeaning(4), false)
	def("NewArray", 7, []OperandType{Reg8, UInt16}, noMeaning(2), false)
	def("Mov", 8, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("MovLong", 9, []OperandType{Reg32, Reg32}, noMeaning(2), false)
	def("Negate", 10, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Not", 11, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("BitNot", 12, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("TypeOf", 13, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Eq", 14, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("StrictEq", 15, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Neq", 16, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("StrictNeq", 17, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Less", 18, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LessEq", 19, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Greater", 20, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GreaterEq", 21, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Add", 22, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("AddN", 23, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("AddS", 24, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Mul", 25, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("MulN", 26, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Div", 27, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("DivN", 28, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Mod", 29, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Sub", 30, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("SubN", 31, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LShift", 32, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("RShift", 33, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("URshift", 34, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitAnd", 35, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitXor", 36, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitOr", 37, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Inc", 38, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Dec", 39, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("InstanceOf", 40, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("IsIn", 41, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetParentEnvironment", 42, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("GetEnvironment", 43, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("GetClosureEnvironment", 44, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("StoreToEnvironment", 45, []OperandType{Reg8, UInt8, Reg8}, noMeaning(3), false)
	def("StoreToEnvironmentL", 46, []OperandType{Reg8, UInt16, Reg8}, noMeaning(3), false)
	def("StoreNPToEnvironment", 47, []OperandType{Reg8, UInt8, Reg8}, noMeaning(3), false)
	def("StoreNPToEnvironmentL", 48, []OperandType{Reg8, UInt16, Reg8}, noMeaning(3), false)
	def("LoadFromEnvironment", 49, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("LoadFromEnvironmentL", 50, []OperandType{Reg8, Reg8, UInt16}, noMeaning(3), false)
	def("GetGlobalObject", 51, []OperandType{Reg8}, noMeaning(1), false)
	def("GetNewTarget", 52, []OperandType{Reg8}, noMeaning(1), false)
	def("CreateFunctionEnvironment", 53, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("CreateTopLevelEnvironment", 54, []OperandType{Reg8, UInt32}, noMeaning(2), false)
	def("CreateEnvironment", 55, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("DeclareGlobalVar", 56, []OperandType{UInt32}, []OperandMeaning{MeaningStringID}, false)
	def("GetByIdShort", 57, []OperandType{Reg8, Reg8, UInt8, UInt8}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetById", 58, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetByIdLong", 59, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryGetById", 60, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryGetByIdLong", 61, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdLoose", 62, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdStrict", 63, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdLooseLong", 64, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdStrictLong", 65, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdLoose", 66, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdStrict", 67, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdLooseLong", 68, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdStrictLong", 69, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutNewOwnByIdShort", 70, []OperandType{Reg8, Reg8, UInt8}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutNewOwnById", 71, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutNewOwnByIdLong", 72, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutOwnBySlotIdx", 73, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("PutOwnBySlotIdxLong", 74, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("PutNewOwnNEById", 75, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutNewOwnNEByIdLong", 76, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutOwnByIndex", 77, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("PutOwnByIndexL", 78, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("PutOwnByVal", 79, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), false)
	def("DelByIdLoose", 80, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("DelByIdStrict", 81, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("DelByIdLooseLong", 82, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("DelByIdStrictLong", 83, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetByVal", 84, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetByIndex", 85, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("PutByValLoose", 86, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("PutByValStrict", 87, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("DelByValLoose", 88, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("DelByValStrict", 89, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("PutOwnGetterSetterByVal", 90, []OperandType{Reg8, Reg8, Reg8, Reg8, UInt8}, noMeaning(5), false)
	def("GetPNameList", 91, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), false)
	def("GetNextPName", 92, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(5), false)
	def("Call", 93, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), true)
	def("Construct", 94, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), true)
	def("Call1", 95, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), true)
	def("CallWithNewTarget", 96, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), true)
	def("Call2", 97, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), true)
	def("Call3", 98, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(5), true)
	def("Call4", 99, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(6), true)
	def("CallWithNewTargetLong", 100, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), true)
	def("CallBuiltin", 101, []OperandType{Reg8, UInt8, UInt8}, noMeaning(3), false)
	def("CallBuiltinLong", 102, []OperandType{Reg8, UInt8, UInt32}, noMeaning(3), false)
	def("GetBuiltinClosure", 103, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("Ret", 104, []OperandType{Reg8}, noMeaning(1), false)
	def("Catch", 105, []OperandType{Reg8}, noMeaning(1), false)
	def("DirectEval", 106, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("Throw", 107, []OperandType{Reg8}, noMeaning(1), false)
	def("ThrowIfEmpty", 108, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Debugger", 109, nil, nil, false)
	def("AsyncBreakCheck", 110, nil, nil, false)
	def("ProfilePoint", 111, []OperandType{UInt16}, noMeaning(1), false)
	def("CreateClosure", 112, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateClosureLongIndex", 113, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateThis", 114, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("SelectObject", 115, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LoadParam", 116, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("LoadParamLong", 117, []OperandType{Reg8, UInt32}, noMeaning(2), false)
	def("LoadConstUInt8", 118, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("LoadConstInt", 119, []OperandType{Reg8, Imm32}, noMeaning(2), false)
	def("LoadConstDouble", 120, []OperandType{Reg8, DoubleT}, noMeaning(2), false)
	def("LoadConstBigInt", 121, []OperandType{Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningBigIntID}, false)
	def("LoadConstBigIntLongIndex", 122, []OperandType{Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningBigIntID}, false)
	def("LoadConstString", 123, []OperandType{Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningStringID}, false)
	def("LoadConstStringLongIndex", 124, []OperandType{Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningStringID}, false)
	def("LoadConstEmpty", 125, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstUndefined", 126, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstNull", 127, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstTrue", 128, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstFalse", 129, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstZero", 130, []OperandType{Reg8}, noMeaning(1), false)
	def("CoerceThisNS", 131, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("LoadThisNS", 132, []OperandType{Reg8}, noMeaning(1), false)
	def("ToNumber", 133, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ToNumeric", 134, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ToInt32", 135, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("AddEmptyString", 136, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("GetArgumentsPropByValLoose", 137, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetArgumentsPropByValStrict", 138, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetArgumentsLength", 139, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ReifyArgumentsStrict", 140, []OperandType{Reg8}, noMeaning(1), false)
	def("ReifyArgumentsLoose", 141, []OperandType{Reg8}, noMeaning(1), false)
	def("CreateRegExp", 142, []OperandType{Reg8, UInt32, UInt32, UInt32}, []OperandMeaning{MeaningNone, MeaningStringID, MeaningStringID, MeaningNone}, false)
	def("SwitchImm", 143, []OperandType{Reg8, UInt32, Addr32, UInt32, UInt32}, noMeaning(5), false)
	def("CreateGenerator", 144, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateGeneratorLongIndex", 145, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("IteratorBegin", 146, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("IteratorNext", 147, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("IteratorClose", 148, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("Jmp", 149, []OperandType{Addr8}, noMeaning(1), false)
	def("JmpLong", 150, []OperandType{Addr32}, noMeaning(1), false)
	def("JmpTrue", 151, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpTrueLong", 152, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JmpFalse", 153, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpFalseLong", 154, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JmpUndefined", 155, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpUndefinedLong", 156, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JLess", 157, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessLong", 158, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLess", 159, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessLong", 160, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessN", 161, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessNLong", 162, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessN", 163, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessNLong", 164, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqual", 165, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualLong", 166, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqual", 167, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualLong", 168, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualN", 169, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualNLong", 170, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualN", 171, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualNLong", 172, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreater", 173, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterLong", 174, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreater", 175, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterLong", 176, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterN", 177, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterNLong", 178, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterN", 179, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterNLong", 180, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqual", 181, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqualLong", 182, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqual", 183, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqualLong", 184, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqualN", 185, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqualNLong", 186, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqualN", 187, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqualNLong", 188, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JEqual", 189, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JEqualLong", 190, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotEqual", 191, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotEqualLong", 192, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictEqual", 193, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictEqualLong", 194, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictNotEqual", 195, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictNotEqualLong", 196, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)

	return t
}
// buildOpcodeTable98 returns the Hermes bytecode opcode table for
// bytecode format version 98, ported directly from hermes-dec's
// hbc_opcodes/hbc98.py (the reference Python implementation), so it
// stays byte-for-byte consistent with what the real hermes-dec disassembler
// decodes for files of this version.
func buildOpcodeTable98() map[byte]*InstructionDef {
	t := make(map[byte]*InstructionDef)

	def := func(name string, opcode int, operands []OperandType, meanings []OperandMeaning, hasRet bool) {
		t[byte(opcode)] = NewInst(name, opcode, operands, meanings, hasRet)
	}

	noMeaning := func(n int) []OperandMeaning {
		m := make([]OperandMeaning, n)
		for i := range m {
			m[i] = MeaningNone
		}
		return m
	}

	def("Unreachable", 0, nil, nil, false)
	def("NewObjectWithBuffer", 1, []OperandType{Reg8, UInt16, UInt16}, noMeaning(3), false)
	def("NewObjectWithBufferLong", 2, []OperandType{Reg8, UInt32, UInt32}, noMeaning(3), false)
	def("NewObjectWithBufferAndParent", 3, []OperandType{Reg8, Reg8, UInt32, UInt32}, noMeaning(4), false)
	def("NewObject", 4, []OperandType{Reg8}, noMeaning(1), false)
	def("NewObjectWithParent", 5, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("NewArrayWithBuffer", 6, []OperandType{Reg8, UInt16, UInt16, UInt16}, noMeaning(4), false)
	def("NewArrayWithBufferLong", 7, []OperandType{Reg8, UInt16, UInt16, UInt32}, noMeaning(4), false)
	def("NewArray", 8, []OperandType{Reg8, UInt16}, noMeaning(2), false)
	def("NewFastArray", 9, []OperandType{Reg8, UInt16}, noMeaning(2), false)
	def("FastArrayLength", 10, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("FastArrayLoad", 11, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("FastArrayStore", 12, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("FastArrayPush", 13, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("FastArrayAppend", 14, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("CacheNewObject", 15, []OperandType{Reg8, Reg8, UInt32, UInt8}, noMeaning(4), false)
	def("Mov", 16, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("MovLong", 17, []OperandType{Reg32, Reg32}, noMeaning(2), false)
	def("Negate", 18, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Not", 19, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("BitNot", 20, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("TypeOf", 21, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Eq", 22, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("StrictEq", 23, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Neq", 24, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("StrictNeq", 25, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Less", 26, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LessEq", 27, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Greater", 28, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GreaterEq", 29, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Add", 30, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("AddN", 31, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("AddS", 32, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Mul", 33, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("MulN", 34, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Div", 35, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("DivN", 36, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Mod", 37, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Sub", 38, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("SubN", 39, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LShift", 40, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("RShift", 41, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("URshift", 42, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitAnd", 43, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitXor", 44, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("BitOr", 45, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("Inc", 46, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Dec", 47, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("InstanceOf", 48, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("IsIn", 49, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("PrivateIsIn", 50, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), false)
	def("TypeOfIs", 51, []OperandType{Reg8, Reg8, UInt16}, noMeaning(3), false)
	def("GetParentEnvironment", 52, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("GetEnvironment", 53, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("GetClosureEnvironment", 54, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("StoreToEnvironment", 55, []OperandType{Reg8, UInt8, Reg8}, noMeaning(3), false)
	def("StoreToEnvironmentL", 56, []OperandType{Reg8, UInt16, Reg8}, noMeaning(3), false)
	def("StoreNPToEnvironment", 57, []OperandType{Reg8, UInt8, Reg8}, noMeaning(3), false)
	def("StoreNPToEnvironmentL", 58, []OperandType{Reg8, UInt16, Reg8}, noMeaning(3), false)
	def("LoadFromEnvironment", 59, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("LoadFromEnvironmentL", 60, []OperandType{Reg8, Reg8, UInt16}, noMeaning(3), false)
	def("GetGlobalObject", 61, []OperandType{Reg8}, noMeaning(1), false)
	def("GetNewTarget", 62, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadParentNoTraps", 63, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("CreateFunctionEnvironment", 64, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("CreateTopLevelEnvironment", 65, []OperandType{Reg8, UInt32}, noMeaning(2), false)
	def("CreateEnvironment", 66, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("DeclareGlobalVar", 67, []OperandType{UInt32}, []OperandMeaning{MeaningStringID}, false)
	def("GetByIdShort", 68, []OperandType{Reg8, Reg8, UInt8, UInt8}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetById", 69, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetByIdLong", 70, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("GetByIdWithReceiverLong", 71, []OperandType{Reg8, Reg8, UInt8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryGetById", 72, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryGetByIdLong", 73, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdLoose", 74, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdStrict", 75, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdLooseLong", 76, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutByIdStrictLong", 77, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdLoose", 78, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdStrict", 79, []OperandType{Reg8, Reg8, UInt8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdLooseLong", 80, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("TryPutByIdStrictLong", 81, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("PutOwnBySlotIdx", 82, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("PutOwnBySlotIdxLong", 83, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("GetOwnBySlotIdx", 84, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("GetOwnBySlotIdxLong", 85, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("DefineOwnById", 86, []OperandType{Reg8, Reg8, UInt8, UInt16}, noMeaning(4), false)
	def("DefineOwnByIdLong", 87, []OperandType{Reg8, Reg8, UInt8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningNone, MeaningStringID}, false)
	def("DefineOwnByIndex", 88, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("DefineOwnByIndexL", 89, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), false)
	def("DefineOwnInDenseArray", 90, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("DefineOwnInDenseArrayL", 91, []OperandType{Reg8, Reg8, UInt16}, noMeaning(3), false)
	def("DefineOwnByVal", 92, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), false)
	def("GetByVal", 93, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetByIndex", 94, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("GetByValWithReceiver", 95, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), false)
	def("PutByValLoose", 96, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("PutByValStrict", 97, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("PutByValWithReceiver", 98, []OperandType{Reg8, Reg8, Reg8, Reg8, UInt8}, noMeaning(5), false)
	def("DelByVal", 99, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), false)
	def("AddOwnPrivateBySym", 100, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetOwnPrivateBySym", 101, []OperandType{Reg8, Reg8, UInt8, Reg8}, noMeaning(4), false)
	def("PutOwnPrivateBySym", 102, []OperandType{Reg8, Reg8, UInt8, Reg8}, noMeaning(4), false)
	def("DefineOwnGetterSetterByVal", 103, []OperandType{Reg8, Reg8, Reg8, Reg8, UInt8}, noMeaning(5), false)
	def("GetPNameList", 104, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), false)
	def("GetNextPName", 105, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(5), false)
	def("Call", 106, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), true)
	def("Construct", 107, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), true)
	def("Call1", 108, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), true)
	def("CallWithNewTarget", 109, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), true)
	def("Call2", 110, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), true)
	def("Call3", 111, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(5), true)
	def("Call4", 112, []OperandType{Reg8, Reg8, Reg8, Reg8, Reg8, Reg8}, noMeaning(6), true)
	def("CallWithNewTargetLong", 113, []OperandType{Reg8, Reg8, Reg8, Reg8}, noMeaning(4), true)
	def("CallRequire", 114, []OperandType{Reg8, Reg8, UInt32}, noMeaning(3), true)
	def("CallBuiltin", 115, []OperandType{Reg8, UInt8, UInt8}, noMeaning(3), false)
	def("CallBuiltinLong", 116, []OperandType{Reg8, UInt8, UInt32}, noMeaning(3), false)
	def("GetBuiltinClosure", 117, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("Ret", 118, []OperandType{Reg8}, noMeaning(1), false)
	def("Catch", 119, []OperandType{Reg8}, noMeaning(1), false)
	def("DirectEval", 120, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("Throw", 121, []OperandType{Reg8}, noMeaning(1), false)
	def("ThrowIfEmpty", 122, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ThrowIfUndefined", 123, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ThrowIfThisInitialized", 124, []OperandType{Reg8}, noMeaning(1), false)
	def("Debugger", 125, nil, nil, false)
	def("AsyncBreakCheck", 126, nil, nil, false)
	def("ProfilePoint", 127, []OperandType{UInt16}, noMeaning(1), false)
	def("CreateBaseClass", 128, []OperandType{Reg8, Reg8, Reg8, UInt16}, noMeaning(4), false)
	def("CreateBaseClassLongIndex", 129, []OperandType{Reg8, Reg8, Reg8, UInt32}, noMeaning(4), false)
	def("CreateDerivedClass", 130, []OperandType{Reg8, Reg8, Reg8, Reg8, UInt16}, noMeaning(5), false)
	def("CreateDerivedClassLongIndex", 131, []OperandType{Reg8, Reg8, Reg8, Reg8, UInt32}, noMeaning(5), false)
	def("CreateClosure", 132, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateClosureLongIndex", 133, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateThisForNew", 134, []OperandType{Reg8, Reg8, UInt8}, noMeaning(3), false)
	def("CreateThisForSuper", 135, []OperandType{Reg8, Reg8, Reg8, UInt8}, noMeaning(4), false)
	def("SelectObject", 136, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("LoadParam", 137, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("LoadParamLong", 138, []OperandType{Reg8, UInt32}, noMeaning(2), false)
	def("LoadConstUInt8", 139, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("LoadConstInt", 140, []OperandType{Reg8, Imm32}, noMeaning(2), false)
	def("LoadConstDouble", 141, []OperandType{Reg8, DoubleT}, noMeaning(2), false)
	def("LoadConstBigInt", 142, []OperandType{Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningBigIntID}, false)
	def("LoadConstBigIntLongIndex", 143, []OperandType{Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningBigIntID}, false)
	def("LoadConstString", 144, []OperandType{Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningStringID}, false)
	def("LoadConstStringLongIndex", 145, []OperandType{Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningStringID}, false)
	def("LoadConstEmpty", 146, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstUndefined", 147, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstNull", 148, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstTrue", 149, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstFalse", 150, []OperandType{Reg8}, noMeaning(1), false)
	def("LoadConstZero", 151, []OperandType{Reg8}, noMeaning(1), false)
	def("CoerceThisNS", 152, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("LoadThisNS", 153, []OperandType{Reg8}, noMeaning(1), false)
	def("ToNumber", 154, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ToNumeric", 155, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ToInt32", 156, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("AddEmptyString", 157, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("CreatePrivateName", 158, []OperandType{Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningStringID}, false)
	def("GetArgumentsPropByValLoose", 159, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetArgumentsPropByValStrict", 160, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("GetArgumentsLength", 161, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("ReifyArgumentsStrict", 162, []OperandType{Reg8}, noMeaning(1), false)
	def("ReifyArgumentsLoose", 163, []OperandType{Reg8}, noMeaning(1), false)
	def("ToPropertyKey", 164, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("CreateRegExp", 165, []OperandType{Reg8, UInt32, UInt32, UInt32}, []OperandMeaning{MeaningNone, MeaningStringID, MeaningStringID, MeaningNone}, false)
	def("UIntSwitchImm", 166, []OperandType{Reg8, UInt32, Addr32, UInt32, UInt32}, noMeaning(5), false)
	def("StringSwitchImm", 167, []OperandType{Reg8, UInt32, UInt32, Addr32, UInt32}, noMeaning(5), false)
	def("CreateGenerator", 168, []OperandType{Reg8, Reg8, UInt16}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("CreateGeneratorLongIndex", 169, []OperandType{Reg8, Reg8, UInt32}, []OperandMeaning{MeaningNone, MeaningNone, MeaningFunctionID}, false)
	def("IteratorBegin", 170, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("IteratorNext", 171, []OperandType{Reg8, Reg8, Reg8}, noMeaning(3), false)
	def("IteratorClose", 172, []OperandType{Reg8, UInt8}, noMeaning(2), false)
	def("TypedLoadParent", 173, []OperandType{Reg8, Reg8}, noMeaning(2), false)
	def("Jmp", 174, []OperandType{Addr8}, noMeaning(1), false)
	def("JmpLong", 175, []OperandType{Addr32}, noMeaning(1), false)
	def("JmpTrue", 176, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpTrueLong", 177, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JmpFalse", 178, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpFalseLong", 179, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JmpUndefined", 180, []OperandType{Addr8, Reg8}, noMeaning(2), false)
	def("JmpUndefinedLong", 181, []OperandType{Addr32, Reg8}, noMeaning(2), false)
	def("JmpTypeOfIs", 182, []OperandType{Addr32, Reg8, UInt16}, noMeaning(3), false)
	def("JLess", 183, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessLong", 184, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLess", 185, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessLong", 186, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessN", 187, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessNLong", 188, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessN", 189, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessNLong", 190, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqual", 191, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualLong", 192, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqual", 193, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualLong", 194, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualN", 195, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JLessEqualNLong", 196, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualN", 197, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotLessEqualNLong", 198, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreater", 199, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterLong", 200, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreater", 201, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterLong", 202, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqual", 203, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JGreaterEqualLong", 204, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqual", 205, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotGreaterEqualLong", 206, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JEqual", 207, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JEqualLong", 208, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JNotEqual", 209, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JNotEqualLong", 210, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictEqual", 211, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictEqualLong", 212, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictNotEqual", 213, []OperandType{Addr8, Reg8, Reg8}, noMeaning(3), false)
	def("JStrictNotEqualLong", 214, []OperandType{Addr32, Reg8, Reg8}, noMeaning(3), false)
	def("JmpBuiltinIs", 215, []OperandType{Addr8, UInt8, Reg8}, noMeaning(3), false)
	def("JmpBuiltinIsLong", 216, []OperandType{Addr32, UInt8, Reg8}, noMeaning(3), false)
	def("JmpBuiltinIsNot", 217, []OperandType{Addr8, UInt8, Reg8}, noMeaning(3), false)
	def("JmpBuiltinIsNotLong", 218, []OperandType{Addr32, UInt8, Reg8}, noMeaning(3), false)

	return t
}